### ISSUE TITLE
What is the callback url for github?

### ISSUE THREAD

**Issue by Ehekatl** [gocd-contrib/gocd-oauth-login#1]
I got a http 500 error if just fill with server base url, and I test some url it just return http 404 redirect_uri_mismatch, how to fill in the callback url?

**Comment by srinivasupadhya** [comment]
http://www.go.cd/images/blog/authentication-plugins/generate-oauth-token.png

you need to configure it like this. replace `http://localhost:8153` to match the server base url in plugin configuration. will update readme with these details.

**Comment by Ehekatl** [comment]
Still error
![](http://7xicnm.com1.z0.glb.clouddn.com/tmp_screencapture.png)

**Comment by srinivasupadhya** [comment]
provide the following:
In GitHub page:
`Homepage URL`:
`Authorization Callback URL`:

In plugin configuration:
`Server Base URL`:

and please post the `plugin-github.oauth.login.log` content on login attempt.

**Comment by Ehekatl** [comment]
I check my configuration very carefully and follow your instruction, I think they was no problem. (just don't wanna post my server publicly)
if I fill callback url as the one you give me, after access `go/plugin/interact/github.oauth.login/index` I just directly get a error (from the link)

```
 http://******/go/plugin/interact/github.oauth.login/authenticate?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fv3%2Foauth%2F%23redirect-uri-mismatch
```

I can't see this [page](https://github.com/srinivasupadhya/gocd-oauth-login/blob/master/images/github-login.png)

but if I fill the callback url as same as home page, github authenticate page will show up and return 
`http://*****/go/plugin/interact/github.oauth.login/authenticate?code=********************`, then got the same http 500 error as before. The log file shows exactly the same problem as I post before.

**Comment by Ehekatl** [comment]
Google's Oauth work for me...more likely a bug here.

**Comment by srinivasupadhya** [comment]
the plugin is setup on https://build.go.cd

the authorization callback (in github settings page) is setup to be: `https://build.go.cd/go/plugin/interact/github.oauth.login/authenticate`

and server base url (in Go server plugin settings) is setup to be: `https://build.go.cd`

and it seems to be working.

**Comment by srinivasupadhya** [comment]
i uploaded new set of jars - `v1.0`. can you give them a shot?

**Comment by Ehekatl** [comment]
Thanks, it works now

**Comment by srinivasupadhya** [comment]
Great :+1:

**Comment by balboah** [comment]
Got the same kind of errors, took some url juggling before I figured it out. Maybe stripping trailing `/` from base url or read the default base path uri is possible to reduce the confusion?

**Comment by srinivasupadhya** [comment]
Sorry about that. Updated Readme. Hope that helps.
