### ISSUE TITLE
Feature Request: add team membership as a check for GitHub OAuth

### ISSUE THREAD

**Issue by rafaelmagu** [gocd-contrib/gocd-oauth-login#10]
It would be great if we could restrict access only to members of a particular GitHub team when using the GitHub provider.

**Comment by srinivasupadhya** [comment]
workaround: add users & select [allowOnlyKnownUsersToLogin](http://www.go.cd/documentation/user/current/configuration/configuration_reference.html#security)

**Comment by rafaelmagu** [comment]
Yeah, I saw that workaround in the other issue on this repo, but that's far from ideal, especially in large-ish GitHub teams (and there's no way to to regex as our usernames don't follow a pattern). I had a look at the code but it went over my head. Do you have a link to the actual docs for the SocialAuthManager library you're using? (My Google-fu returned bogus results)

**Comment by srinivasupadhya** [comment]
social auth code is here - https://github.com/3pillarlabs/socialauth
they provide ability to write a plugin to their code. example - https://github.com/cvsintellect/linkedin-import

**Comment by srinivasupadhya** [comment]
done with https://github.com/srinivasupadhya/gocd-oauth-login/pull/14
