### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by davidpaniz** [gocd-contrib/gocd-oauth-login#13]
Hi,

I would like to fork your project, but I don't know if I am allowed to because the project seems to be missing a license. I suggest you to add a LICENSE file in order to make it clear and explicit.

Here is a comparison of FOSS licenses: https://en.wikipedia.org/wiki/Comparison_of_free_and_open-source_software_licenses

**Comment by srinivasupadhya** [comment]
done :+1:
