### ISSUE TITLE
plug-in configuration file location

### ISSUE THREAD

**Issue by pejvan** [gocd-contrib/gocd-oauth-login#16]
Hi Srinivas,

I'm looking for a way to backup the plug-in configuration, but I can't find the file location.
Sorry for creating an issue for that, but could you please let me know where I can find it?

Many thanks.

**Comment by srinivasupadhya** [comment]
the plugin configuration sits inside the DB, so backup of the db takes care of it.

**Comment by pejvan** [comment]
OK thanks.
