### ISSUE TITLE
Google icon is loaded over http

### ISSUE THREAD

**Issue by JorritSalverda** [gocd-contrib/gocd-oauth-login#18]
The icon shown for google is loaded over http causing an error when using gocd over https.

http://icons.iconarchive.com/icons/sicons/basic-round-social/48/google-icon.png

The iconarchive seems to redirect https to http.

**Comment by srinivasupadhya** [comment]
thanks for reporting :+1:  will see how this can be fixed. just making the link http to https works?

**Comment by JorritSalverda** [comment]
No, iconarchive redirects https://icons.iconarchive.com/icons/sicons/basic-round-social/48/google-icon.png to http://icons.iconarchive.com/icons/sicons/basic-round-social/48/google-icon.png, so I'm afraid that it has to come from another source than iconarchive.

**Comment by srinivasupadhya** [comment]
ok will try to find a good image for this.

**Comment by ketan** [comment]
This is now resolved with release 1.1 of the plugin. Please update the plugin to not get this warning.
