### ISSUE TITLE
Is Server Base URL necessary?

### ISSUE THREAD

**Issue by raymondbutcher** [gocd-contrib/gocd-oauth-login#19]
I'm attempting to make my server URL dynamic, by updating siteUrl/secureSiteUrl in /etc/go/cruise-config.xml before starting the service.

This seems like it should be fine, but this plugin has its own Server Base URL stored in the database.

So I am wondering: would it be possible for this plugin to access the value of siteUrl/secureSiteUrl rather than have its own separate setting?

Thanks.

**Comment by srinivasupadhya** [comment]
The base url is used to construct the server redirect url for github. Even if somehow the plugin figures out the new base url everytime, how will you update 'Authorization Callback URL' on github [here](https://github.com/srinivasupadhya/gocd-oauth-login/blob/master/images/generate-oauth-token.png)?

**Comment by ketan** [comment]
The plugin currently cannot access the server settings. Please open this issue on gocd/gocd to allow the plugin to access the server settings.
