### ISSUE TITLE
Could we only allow enabled user login through Oauth?

### ISSUE THREAD

**Issue by Ehekatl** [gocd-contrib/gocd-oauth-login#2]
Add user from github is awesome, but for security concerns, Oauth login should not open to everyone...How you deal with this problem?

**Comment by srinivasupadhya** [comment]
you can choose to allow only known users to login - http://www.go.cd/documentation/user/current/configuration/configuration_reference.html#security

**Comment by Ehekatl** [comment]
thanks again, really help a lot, btw I got some trouble when I use user api to delete user,
when the user name is a email address, I will get this : 

```
curl -k 'https://******.com/go/api/users/********@gmail.com'       -u '******:******'       -H 'Accept: application/vnd.go.cd.v1+json'       -X DELETE
 {
  "message": "Either the resource you requested was not found, or you are not authorized to perform this action."
}
```

the user is not admin and disabled...why we just have a delete user button?

**Comment by srinivasupadhya** [comment]
welcome!

the delete user api issue is Go's issue. can you raise an issue for that in https://github.com/gocd/gocd?

thanks.

**Comment by srinivasupadhya** [comment]
Can you try:

```
curl -k 'https://******.com/go/api/users/********%40gmail%2Ecom' -u '******:******' -H 'Accept: application/vnd.go.cd.v1+json' -X DELETE
```

basically URL encode `@` & `.`

**Comment by pejvan** [comment]
Hi Srinivas

I have successfully installed and configured the plug-in, however, it still allows anonymous logins, even with the config set as you suggested:

```
  <server ...

    <security allowOnlyKnownUsersToLogin="true">
      <admins>
        <user>pejvan</user>
      </admins>
    </security>
  </server>
```

Any suggestions?

**Comment by srinivasupadhya** [comment]
yes. thats a limitation currently. to enable authentication you will need to add a dummy (with no valid users) LDAP / password file authentication. this is just to enable authentication in Go. once its enabled GitHub authentication will kickin.
