### ISSUE TITLE
Overreaching for Github profile access?

### ISSUE THREAD

**Issue by joejag** [gocd-contrib/gocd-oauth-login#22]
Thanks very much for developing this plugin.

When people log in to the Github a user is prompted to give `read and write` access to:
- Private email
- Profile Information
- Followers

I can understand `read` access to this information, but `write` seems unnecessary.

Is it possible to reduce the level required?

Thanks! Joe.

**Comment by lenucksi** [comment]
I can confirm this. It is pretty strange...
Also I think that it should only require minimum rights, such as authentication and maybe email adress.

**Comment by scottmuc** [comment]
Also an issue for us, which may result in pulling our usage of this plugin :(

**Comment by ketan** [comment]
I feel this is a fairly simple fix to ensure that each oauth plugin implementation (google, github) returns a different set of permissions for the oauth library to do the right things.

Any takers?

**Comment by ketan** [comment]
Fixed via https://github.com/gocd-contrib/gocd-oauth-login/commit/90c9bcb289acf6a9eda56d10d0724c397bd5bb74#diff-214251aa270429845d9a49fd6576063fR55
