### ISSUE TITLE
No login screen after clicking save button 

### ISSUE THREAD

**Issue by cw-deenbandhu** [gocd-contrib/gocd-oauth-login#23]
No screen is shown after save button button is clicked and do i have to store my github username and password in the password file or i can use any set of username and password

Thanks in advance

**Comment by srinivasupadhya** [comment]
same as #8?

**Comment by cw-deenbandhu** [comment]
hi srinivas,

actually as soon as i add a file and set settings in admin tab it ask for the username and password. and  after that i set configuration for plugin so no login screen is shown but logging out and filling the text boxes with github username and password and clicking on github button instead of sign in button takes me to github website so issue solved 

Thanks

**Comment by srinivasupadhya** [comment]
you will not need to fill Go's username & password field with Github credentials. Clicking on Github button should suffice.

**Comment by cw-deenbandhu** [comment]
yeah thats too working
