### ISSUE TITLE
Not able to pull data from github

### ISSUE THREAD

**Issue by cw-deenbandhu** [gocd-contrib/gocd-oauth-login#24]
hi srinivas

all the steps done successfully but still i am not able to pull my private repository codes from git hub

**Comment by betarelease** [comment]
Same experience as above. Followed all the steps.. including added the personal access token in the OAuth field, but not able to oauth with github

**Comment by ketan** [comment]
@cw-deenbandhu @betarelease are you able to reproduce this issue with version 1.1?

**Comment by betarelease** [comment]
Works well for me after the upgrade. I am able to integrate with github now.

**Comment by ketan** [comment]
Thanks @betarelease. I'm closing this issue out.
