### ISSUE TITLE
After copying the .jar file into the plugin folder and restarted the server I get Connection Refused

### ISSUE THREAD

**Issue by sl-fedegiust** [gocd-contrib/gocd-oauth-login#27]
I was following the configuration as you have on the readme but as soon as I copy the .jar file into the plugins/external folder and restarted the server I keep getting connection refused and can't access it anymore.

If I delete the plugin and restart the server it starts working again.

**Comment by ketan** [comment]
Do you have a log from the server that indicates what error there is?

**Comment by ketan** [comment]
Closing, no response.
