### ISSUE TITLE
Lock down to an organization

### ISSUE THREAD

**Issue by scriby** [gocd-contrib/gocd-oauth-login#34]
By default this plugin allows ANYONE on Github to log into the build server. It would be nice if it could lock it down based on organization membership. I am a little confused about how or if the user name regex can be used for this purpose.

**Comment by margueritepd** [comment]
Looks like https://github.com/gocd-contrib/gocd-oauth-login/pull/14 overrode the functionality of `usernameRegex` for the github plugin to instead mean the org you should be part of in order to log in. I think the plugin author had future plans to rearchitect the plugin, and in so doing clean up the naming, but I am unsure if that happened. That's why the naming is confusing :)

**Comment by scriby** [comment]
That would explain why I couldn't get the username regex to work at all... I threw my org name in there and it seems to have worked!

I'm going to leave this issue open as a reminder to update the UI strings and docs etc. so this will make sense to new users.

Thanks for your comment!

**Comment by scriby** [comment]
Another random note... this functionality doesn't work unless you specify a username and oauth token.

Create a "personal access token" with the "org:read" privilege in github (use this as the oauth token)

**Comment by arvindsv** [comment]
I'm not the author, but I think I might have permissions to accept PRs. If you want to improve the README and submit a PR for it, I'll accept it.

Also, the UI string is [here](https://github.com/gocd-contrib/gocd-oauth-login/blob/7e219deb0915b036d850608f6fb8ed3dab83ddc2/src/main/resources/common/plugin-settings.template.html#L32). Just saying. :)

**Comment by arvindsv** [comment]
Also, this seems to be related to https://github.com/gocd-contrib/gocd-oauth-login/issues/36#issuecomment-221334897.

**Comment by tonyzwei** [comment]
I think I got the fix eventually. In setting window of Google OAuth Login, give the value of .*@mycompany.com$ to Username Regular Expression, instead of Username.
allowOnlyKnownUsersToLogin="true" only works for users who have already signed up.

**Comment by ketan** [comment]
There is a new [2.0 release](https://github.com/gocd-contrib/gocd-oauth-login/releases/tag/v2.0) that addresses all the issues highlighted here.

Please be sure re-configure the plugins again, after you install them.
