### ISSUE TITLE
All users are logged out after changing the role of a single user.

### ISSUE THREAD

**Issue by NickH-nz** [gocd-contrib/gocd-oauth-login#38]
##### Issue Type
- Bug Report
##### Summary

After changing a users role, all users including me are logged out.
###### Basic environment details

``` plain
Go Server Version:  16.5.0(3305-5f54cf4338eb2ff5c9f486ede6ae97e9aae51e82)
JVM version:    1.7.0_101
OS Information: Linux 4.2.0-18-generic running in a Docker container
```
###### Other Environment Details

Auth System:    https://github.com/gocd-contrib/gocd-oauth-login using Google login
##### Steps to Reproduce

1. Have any number of users logged in and viewing the dashboard
2. As an administrator, under user summary change the role of any user
3. Observe that all users are logged out, including you
##### Expected Results

No users should be logged out when a role is changed. 
##### Actual Results

After changing the role of any user, all users are logged out, even if they are in the process of editing something.
##### Other Information

Reported this to the gocd server team: https://github.com/gocd/gocd/issues/2324
They tested LDAP and password file based auth and they seemed to work as expected, which lead them to believe it was an issue with this plugin.

**Comment by blalor** [comment]
Also running into this with v2.2 of the plugin and GoCD v16.12.0.  It's really annoying as I set up a new system with new users.

**Comment by greglook** [comment]
FWIW you can avoid this by creating a local 'admin' user in the GoCD password file and logging in as that while making large numbers of auth changes. Still doesn't help the other users, but is less disruptive for the administrator.

**Comment by jyotisingh** [comment]
This is not a plugin issue, but an issue with authentication plugin endpoint (in core). https://github.com/gocd/gocd/issues/2324.
