### ISSUE TITLE
Google authentication should not require google+ account

### ISSUE THREAD

**Issue by margueritepd** [gocd-contrib/gocd-oauth-login#4]
Hello!

The google oauth plugin in its current form requires the authenticating user to register for a google+ account. To change this, I dug into the `socialauth` code and found that this should be configurable via an `oauth_consumer.properties` file by limiting the google+ authorization scope to `profile,email`. However, the way that the plugin invokes `socialauth` causes this file to be ignored by setting its configuration to only what is provided by GoCD.

I was able to inject my own permissions by modifying your plugin like so:

``` diff
diff --git a/src/main/java/com/tw/go/plugin/OAuthLoginPlugin.java b/src/main/java/com/tw/go/plugin/OAuthLoginPlugin.java
index 08bd22a..0fbb8cb 100644
--- a/src/main/java/com/tw/go/plugin/OAuthLoginPlugin.java
+++ b/src/main/java/com/tw/go/plugin/OAuthLoginPlugin.java
@@ -203,13 +203,15 @@ public class OAuthLoginPlugin implements GoPlugin {
         try {
             PluginSettings pluginSettings = getPluginSettings();
             Properties oauthConsumerProperties = new Properties();
+            InputStream consumerPropertiesStream = new FileInputStream("/etc/go/oauth_consumer.properties");
+            oauthConsumerProperties.load(consumerPropertiesStream);
             oauthConsumerProperties.put(provider.getConsumerKeyPropertyName(), pluginSettings.getConsumerKey());
             oauthConsumerProperties.put(provider.getConsumerSecretPropertyName(), pluginSettings.getConsumerSecret());
             SocialAuthConfig socialAuthConfiguration = SocialAuthConfig.getDefault();
             socialAuthConfiguration.load(oauthConsumerProperties);
             SocialAuthManager manager = new SocialAuthManager();
             manager.setSocialAuthConfig(socialAuthConfiguration);
-            String redirectURL = manager.getAuthenticationUrl(provider.getProviderName(), getURL(pluginSettings.getServerBaseURL()), Permission.ALL);
+            String redirectURL = manager.getAuthenticationUrl(provider.getProviderName(), getURL(pluginSettings.getServerBaseURL()));

             store(manager);
```

Obviously this is not a very general solution, but I like it because
- it lets the user tweak arbitrary nobs that `socialauth` offers without needing them to be exposed by GoCD
- it means I can manage this file via a configuration management tool.

Is this idea worth a PR? I can spend some time making this PR-worthy but some ideas on how to make it less platform-specific/janky would be great.

**Comment by srinivasupadhya** [comment]
thanks for posting the issue & all the research work.

ideas:
1. we could take content of `oauth_consumer.properties` from plugin settings like we take consumer id currently. i dint do it to provide better user experience (i.e. i ask for consumer id & consumer secret & create the required properties) - also allows plugin to change underlying library without any change to end user etc.
2. we can make the call 

```
manager.getAuthenticationUrl(provider.getProviderName(), getURL(pluginSettings.getServerBaseURL()), Permission.ALL);

to

manager.getAuthenticationUrl(provider.getProviderName(), getURL(pluginSettings.getServerBaseURL());
```

this should fix the issue?

**Comment by margueritepd** [comment]
That's true, it would be nice to not expose the internals of the oauth library.

For this specific problem, I think we can get away with using a more conservative scope (`Permission.AUTHENTENTICATE_ONLY`). This still provides all the profile properties used by the gocd plugin in both the google and github cases. I can do a PR for that.

Another thing I used `oauth_consumer.properties` for was to add the `hd=somedomain` parameter to the authorization url, which for googleplus api will only authorize users with a google apps domain of `somedomain`. However, this is an insecure way of enforcing that, since the client is responsible for sending the authorization url and could change it to anything they want. Maybe a better way to solve this would be to let the plugin do the checking - thoughts on that? I can open a new issue to discuss this

**Comment by srinivasupadhya** [comment]
> For this specific problem, I think we can get away with using a more conservative scope (Permission.AUTHENTENTICATE_ONLY). This still provides all the profile properties used by the gocd plugin in both the google and github cases. I can do a PR for that.

great. send in a PR. thanks.

> Another thing I used oauth_consumer.properties for was to add the hd=somedomain parameter to the authorization url, which for googleplus api will only authorize users with a google apps domain of somedomain. However, this is an insecure way of enforcing that, since the client is responsible for sending the authorization url and could change it to anything they want. Maybe a better way to solve this would be to let the plugin do the checking - thoughts on that? I can open a new issue to discuss this

i have been thinking about providing that for google plugin. a plugin setting asking for domain & checking `@` to match the domain. login fails if it doesn't match. you can create a new issues for that for better tracking.

**Comment by margueritepd** [comment]
Issue created here: https://github.com/srinivasupadhya/gocd-oauth-login/issues/5

**Comment by srinivasupadhya** [comment]
fixed as part of https://github.com/srinivasupadhya/gocd-oauth-login/pull/6
