### ISSUE TITLE
Google plugin should limit authorized users by google apps domain

### ISSUE THREAD

**Issue by margueritepd** [gocd-contrib/gocd-oauth-login#5]
Hello!

It would be nice to be able to limit by email domain which users are authorized to access GoCD when they authenticate with google.

e.g. if my company has the google apps domain `foo.com`, it would be nice to be able to limit access to GoCD only to google users who log in from that domain.

I'm happy to try this. I was thinking: allow oauth providers have
- a method to return extra fields they want to ask for on the configuration screen
- a post-oauth-authentication hook that says "should this user have access to GoCD"

**Comment by srinivasupadhya** [comment]
I suggest create field in [plugin settings](https://github.com/srinivasupadhya/gocd-oauth-login/blob/master/src/main/java/com/tw/go/plugin/PluginSettings.java#L4) say `userMatchRegex` & add it in [UI](https://github.com/srinivasupadhya/gocd-oauth-login/blob/master/src/main/resources/common/plugin-settings.template.html). This could be a comma separated value.

Add a regex matcher [here](https://github.com/srinivasupadhya/gocd-oauth-login/blob/master/src/main/java/com/tw/go/plugin/OAuthLoginPlugin.java#L248) which will throw a runtime exception if there is a regex setup & the email doesn't match the regex.

**Comment by margueritepd** [comment]
That won't work for the github plugin. Publicly viewable emails are optional in github  (see https://developer.github.com/v3/users/) and you can set to whatever you want. That's why I was thinking that the email matching should only be configurable/available for the google plugin.

**Comment by srinivasupadhya** [comment]
the regex matcher is going to be generic. so for google it will be something like `*@foo.com,*@foo.in` & for github it could be something else. keeping a generic matcher will make it easier for other providers - so if someone adds a MSN login the rest remain same.

**Comment by srinivasupadhya** [comment]
fixed with https://github.com/srinivasupadhya/gocd-oauth-login/pull/7
