### ISSUE TITLE
Plugin not loading using Helm GoCD

### ISSUE THREAD

**Issue by psandhu79** [gocd-contrib/gocd-oauth-login#54]
Hi

i have  installed GoCD using helm and created a persisted volume and added the google oath plugin to the external folder

I enabled the filepassword auth however google outh plugin does not apper

in the logs i see

I  2018-06-29 11:57:59,697 ERROR [Thread-78] PluginSettingsMetadataLoader:65 - Plugin: google.oauth.login - Metadata load info: []
 
I  2018-06-29 11:57:59,696 ERROR [Thread-78] PluginSettingsMetadataLoader:64 - Failed to fetch plugin settings metadata for plugin google.oauth.login. Maybe the plugin does not implement plugin settings and view?

**Comment by varshavaradarajan** [comment]
@psandhu79 - the authentication plugins have been deprecated since the beginning of this year when we moved to support authorization. Use https://github.com/gocd-contrib/google-oauth-authorization-plugin instead.

**Comment by varshavaradarajan** [comment]
@psandhu79 - the readme is already updated in this repo with the same. Closing the issue
