### ISSUE TITLE
Plug-in doesn't seem to be enabled after server restart

### ISSUE THREAD

**Issue by rafaelmagu** [gocd-contrib/gocd-oauth-login#8]
I've followed the documentation to set it up, but found no way to actually enable the plugin after clicking Save on the configuration. Have also restarted the Go server but auth is still disabled. How do I enable the plugin to require auth from users?

**Comment by srinivasupadhya** [comment]
to enable authentication you will need to enable LDAP / password file. there is an issue with Go to be able to use authentication plugin alone. for now you can just add a password file path & things should work.

**Comment by srinivasupadhya** [comment]
assuming that worked.
