### ISSUE TITLE
Documentation is not specific on what permissions are required for personal tokens

### ISSUE THREAD

**Issue by rafaelmagu** [gocd-contrib/gocd-oauth-login#9]
When setting up GitHub OAuth, the documentation does not list the permissions required for the authentication process to work.

I've set up a token with just:
- user:email
- read:org
- user

Though I'm not sure if it works, as there's no indication it is (no interstitial page to log in), per #8

**Comment by srinivasupadhya** [comment]
`user` should be enough. its just to provide ability to `search` users & add them.

**Comment by rafaelmagu** [comment]
Cool, I'll update my permissions.
